### ISSUE TITLE
Translating C++ exceptions into python exceptions

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#15]
As we discussed in our call yesterday, the boost documentation on wrapping C++ exceptions to be handled by python is awful to say the least.  I was poking around and found this useful reference in stackoverflow.   

https://stackoverflow.com/questions/2261858/boostpython-export-custom-exception

Assuming it is correct, it provides a pretty clear and simple solution.  The example translates almost exactly to the current C++ implementation since the example shown is extremely similar to the base class MsPASSException.

**Comment by wangyinz** [comment]
That's what I thought, so I did not really dig into that. Glad that you find a clean solution. I think in addition to adopting this, we also need to think about how we should deal with the python bindings generated automatically. Do we want to do the automatic translate whenever a new piece of code is written? Maybe we should manually rewrite those and future codes into something human friendly. This should be straightforward but tedious.

**Comment by pavlis** [comment]
I don't think it looks that tedious to write these by hand, but since I didn't actually do this yet I may be just naive.  I'll work on the exception handler as soon as you finish your paper and can help me understand how you built the wrappers in the new branch.

**Comment by pavlis** [comment]
I'm going to close this issue.  With time I've learned there really isn't an issue.  pybind11 wrappers translate MsPASSError objects to RunTimeError exceptions.  Because MsPASSError is wisely made a child of std::exception inheritance handles the conversion with no issues and when a python script doesn't handle an exception it will abort printing the std::exception.what() method which MsPASSError overrides.   Point is anything throwing a MsPASSError just needs to be handled with a RunTimeError exception handler.
