### ISSUE TITLE
Invalid example in the user manual

### ISSUE THREAD

**Issue by seisman** [wangyinz/mspass#172]
In this section (https://wangyinz.github.io/mspass/user_manual/data_object_design_concepts.html#scalar-versus-3c-data), the code shows how to create a simple seismogram, but the code is no longer valid.
```
from mspasspy import Seismogram
d=Seismogram(100)  # Create an empty Seismogram with storage for 100 time steps initialized to all zeros
d.data(0,50)=1.0      # Create a delta function at time t0+dt*50 in component 0
```

**Comment by seisman** [comment]
A working example:
```
from mspasspy.ccore.seismic import Seismogram
d = Seismogram(100)
d.data[:,50] = 1.0
```

**Comment by wangyinz** [comment]
Thanks for capturing that! We are in the process of revising the documentation right now, and that section is one of those written a long time ago. The correct code should be:
```
from mspasspy.ccore.seismic import Seismogram
d = Seismogram(100)
d.data[0,50]=1.0
```
Yes, there was also a syntax error in the original one...

**Comment by wangyinz** [comment]
> A working example:
> 
> ```
> from mspasspy.ccore.seismic import Seismogram
> d = Seismogram(100)
> d.data[:,50] = 1.0
> ```

Glad you were able to figure it out yourself!

**Comment by seisman** [comment]
Please let me know if you want me to submit a fix.

**Comment by wangyinz** [comment]
It would be great if you would like to contribute, but I can see that a lot of these old documents are broken and need significant revision, so it may not be the best strategy to fix one from the many. So, either ways works fine for me, and thank you so much for your help if you decided to submit a fix.
