### ISSUE TITLE
ubuntu anomaly with docker

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#18]
Just built a new machine I'm going to be using as a playground for mspass.  I set it up to run ubuntu 18.04, which is the latest standardized release.   The oddity I encountered was that I had to do a sudo on the docker pull wangyinz/mspass.   Without the sudo I got this:
pavlis@pavlis-home-linux:~/mspass_docker$ docker pull wangyinz/mspass
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/create?fromImage=wangyinz%2Fmspass&tag=latest: dial unix /var/run/docker.sock: connect: permission denied

Not an immediate problem, but something we'll need to fix when we have a real release.

**Comment by pavlis** [comment]
Small addition:  seems any call to docker for this machine requires sudo.   The docker run command created the same error.   Perhaps this is a docker setup error?

**Comment by pavlis** [comment]
Think I found the solution.   There was a post install step I missed.   It is described here:
https://docs.docker.com/v17.12/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

I will double check that this worked (procedure requires me to log off) and if it does I'll edit the wiki page.

**Comment by pavlis** [comment]
Well, that didn't do it.   The page suggested I needed this command:
sudo usermod -G docker -a pavlis

then logout and login again - didn't seem to work.   Hmmm

**Comment by pavlis** [comment]
Yet another issue.  I can test with sudo docker so I ran through the rest of your tests in the wiki.   When I try the spark stuff I get a complaint that docker-compose is not found.   This must be another install anomaly.

**Comment by wangyinz** [comment]
It seems docker-compose is a separate package on Linux, and you should be able to install it following [this link](https://docs.docker.com/compose/install/). I do think most of the docker command requires sudo on Linux. Since you own the machine, it is probably easier to just call sudo for all the docker commands.
