### ISSUE TITLE
undetected bug in Database class

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#181]
In the process of adding the miniseed read methods to the Database class I found an unambiguous bug in the `read_data` method of Database.   This set of line is in the 230s (line numbers are mismatched because of my edits, but somewhere in that vicinity) spyder flagged as an error:
```
        if mode == "cautious":
            for k in md:
                if read_metadata_schema.is_defined(k):
                    col = read_metadata_schema.collection(k)
                    unique_key = self.database_schema[col].unique_name(k)
                    if not isinstance(md[k], read_metadata_schema.type(k)):
                        # try to convert the mismatch attribute
                        try:
                            insert_dict[k] = read_metadata_schema.type(k)(md[k])
                        except:
                            if self.database_schema[col].is_required(unique_key):
                                fatal_keys.append(k)
                                is_dead = True
                                log_error_msg.append("cautious mode: Required attribute {} has type {}, forbidden by definition and unable to convert".format(k, type(md[k])))
```
spyder correctly flags that `insert_dict` is not defined.   I recognize that as a relic from an earlier way of handling the issue this is section of code trying to handle.  I'm a bit reluctant to mess with this as there is some complexity in this section of code it would take me a while to sort out. I'm thinking one of you could fix this quickly and more efficiently.  If not, punt it back to me.

**Comment by haruming** [comment]
Good catch! I didn't notice this unambiguous bug before, which I think is a relic that is copy-pasted incorrectly. I have created a pull request for the fix. It just replaces the insert_dict[k] to md[k], which overwrites the attribute value if we could convert it to the correct type.
