### ISSUE TITLE
bug in update_metadata

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#202]
I was testing all our existing tutorials.   Was working through the getting_started tutorial (arguably the most important one we have) and I found a clear bug.   You should be able to recreate the error by running the tutorial,  The very last notebook cell fails with this long message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-12253ab980f6> in <module>
     28         for e in d.elog.get_error_log():
     29             print(e.algorithm,e.badness,e.message)
---> 30     db.save_ensemble_data(ens3c)

~/.local/lib/python3.8/site-packages/mspasspy/db/database.py in save_ensemble_data(self, ensemble_object, mode, storage_mode, dir_list, dfile_list, exclude_keys, exclude_objects, collection, data_tag)
   1515             for i in range(len(ensemble_object.member)):
   1516                 if i not in exclude_objects:
-> 1517                     self.save_data(ensemble_object.member[i], mode=mode, storage_mode=storage_mode, dir=dir_list[j],
   1518                                    dfile=dfile_list[j], exclude_keys=exclude_keys, collection=collection, data_tag=data_tag)
   1519                     j += 1

~/.local/lib/python3.8/site-packages/mspasspy/db/database.py in save_data(self, mspass_object, mode, storage_mode, dir, dfile, format, exclude_keys, collection, data_tag)
    386         if mspass_object.live:
    387             # 1. save metadata, with update mode
--> 388             update_res_code = self.update_metadata(mspass_object, mode, exclude_keys, collection, True, data_tag)
    389 
    390             if mspass_object.live:

~/.local/lib/python3.8/site-packages/mspasspy/db/database.py in update_metadata(self, mspass_object, mode, exclude_keys, collection, ignore_metadata_changed_test, data_tag)
   1392                 if not mspass_object.is_empty():
   1393                     history_obj_id_name = self.database_schema.default_name('history_object') + '_id'
-> 1394                     old_history_object_id = None if new_insertion or history_obj_id_name not in object_doc else object_doc[history_obj_id_name]
   1395                     history_object_id = self._save_history(mspass_object, old_history_object_id)
   1396                     insert_dict.update({history_obj_id_name: history_object_id})

TypeError: argument of type 'NoneType' is not iterable
```
The way In interpret this message is that the variable `object_doc` is set to None.  That is is the only candidate on that line as far as I can judge that could throw the error about being not iterable.   When I look earlier in the update_metadata method I see the problem right here:
```
            object_doc = None

            new_insertion = False
            if '_id' not in mspass_object:
                new_insertion = True

            if not new_insertion:
                object_doc = col.find_one({'_id': mspass_object['_id']})
```
The object_doc variable does not appear between where it is set (just above) and used (line 1394 that generates the error).   The logic landing here clearly leaves object_doc as None.   I'm not sure whether the best fix is to repair the initialization logic or the logic that is throwing the error at line 1394.   Given the complexities of that function I am punting this to you guys to fix as I fear I could create other side effects if I try to patch this myself.

**Comment by pavlis** [comment]
When I check I realize I did several changes to the getting_started tutorial so you won't be able to just run the notebook to recreate the error above.  Unfortunately, git diff is problematic finding changes in a notebook.  I remember these:
1.  The dbclient creation line has to change.
2. All the read_data lines have to change as the old notebook had a relic arg that is no longer used.
3. This read in the final box needs an additional change to add the normalize argument.
```
    for doc in cursor:
        d=db.read_data(doc,normalize=['channel','source'])
        ensemble.member.append(d)
```

**Comment by wangyinz** [comment]
Could you please also get this fixed? @haruming

**Comment by haruming** [comment]
Yeah, that's a good catch. I will fix it in the bugfix_db_crud branch.
