### ISSUE TITLE
overload_cast errors on carbonate

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#23]
I think I have resolved  some syntax related errors in pybind11 wrapper code following the recent changes complicated by my traveling.   However, I'm facing a strange issue on carbonate that I have hacked and hacked and can't see to resolve.   Wrapper code I KNOW worked on my ubuntu machine at home fails to build on carbonate with every line using the "overload_cast" feature in pybind11 generating a string of errors.   That feature requires the 2014 C++ standard, which is actually the default for pybind11.  I'll tell you what I tried in a moment, but let me first suggest a possible odd source of this problem for carbonate.  When I run cmake from an empty build directory here are the first few lines of the output:
[pavlis@i8 build]$ cmake ..
-- The Fortran compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /bin/f95
-- Check for working Fortran compiler: /bin/f95  -- works
-- Detecting Fortran compiler ABI info

Why is this showing 4.8.5?   I know the modules system sets gcc to a higher level on carbonate.  In fact, I've tried every version of gcc using modules commands, but all have the same issue.   That might not really be the issue, however, as I think that message is about gfortran, but it is the only thing I can see that remains. 

I had previously added this to the cmake configuration:
set (CMAKE_CXX_STANDARD 14)

The pybind11 documentation says to use this:
set(PYBIND11_CPP_STANDARD -std=c++14)

but when I use that I get this when I run make:
[ 71%] Building CXX object python/CMakeFiles/mspasspy.dir/mspass_wrapper.cpp.o
c++: error: unrecognized command line option '-std=c++14'
make[2]: *** [python/CMakeFiles/mspasspy.dir/mspass_wrapper.cpp.o] Error 1
make[1]: *** [python/CMakeFiles/mspasspy.dir/all] Error 2

This is why I somewhat suspect the gcc version skew - perhaps I'm somehow using the most ancient version of gcc that doesn't support the 2014 standard.   Totally a guess, but the only one I have left.

This has me baffled.   I'm going check the changes I made into github and let you hack at this if you can today.  Would like to know if you can, for example, make this work on your mac?   I'd try that first and if that succeed see if you can duplicate my problem on carbonate.

I'm submitting this before sending in those commits so make sure you see them before attempting this.    I could get interrupted before I finish

**Comment by wangyinz** [comment]
Yeah, I remember we had this issue before, which is discussed in https://github.com/wangyinz/mspass/issues/6#issuecomment-531479593.

**Comment by pavlis** [comment]
That indeed was the problem.  An example of the old guy suffering from CRS.  That fixed that issue and it now builds after a few small other changes.   I need to now create some tests.  I seem to have not uploaded the existing test script I had started at home so this may be delayed a while.   Need to verify travis will now build this correctly.   Note I change the top level cmake configuration file to keep carbonate from building boost every time.  The older version they have installed seems to work fine for everything at this point

**Comment by pavlis** [comment]
I think I will close this issue.   As noted in the previous your reminder solved the problem.
