### ISSUE TITLE
Bug in handling envname PFPATH

### ISSUE THREAD

**Issue by wangyinz** [wangyinz/mspass#53]
I was doing some test today and encountered a seg fault. It happens at this line:
https://github.com/wangyinz/mspass/blob/c6b354ebc70e8e133a6886f0f33ff34b8e68cb42/cxx/src/lib/utility/AntelopePf.cc#L365
when `s` is a null pointer. This happens when `PFPATH` is not defined in the env, and the if branch up there seems want to handle that situation.

I also wonder if this is a relic from a previous version, as I thought the only env variable we are dependent on should be the `MSPASS_HOME`.

**Comment by pavlis** [comment]
As I mentioned in our phone call earlier today I had found that bug and fixed it, but the fix is on the add_deconvolution branch.
