### ISSUE TITLE
Use monkey patch to on built-in types

### ISSUE THREAD

**Issue by wangyinz** [wangyinz/mspass#54]
I have been working on rearranging the python modules. Currently the design is in the following structure:
```
mspasspy
	ccore
	db
		Client(pymongo.MongoClient)
		Database(pymongo.database.Database)
			load3C
			save3C
			_save_elog
			_save_data3C_to_dfile
			_save_data3C_to_gridfs
			_read_data3C_from_gridfs
			normalize_site
			normalize_source
			_unique_sites
			_unique_sources
		_sync_metadata
		_tmatrix_from_md
	io
		seispp
			index_data: dbsave_indexdata 
			load: calls index_data, normalize_site, normalize_source
		converter
			toTimeSeries
			toSeismogram
			toMetadata
			toTrace
			toStream
```
The changes in db module is pretty much done. As I am working through the io module, I realized something unexpected in my previous design. So, the idea of `mspasspy.io.converter` is to not only provide a series of functions to convert between all different data types, but also use a feature of Python called "monkey patch" to add those `toXXX` methods to certain objects. For example, we can call `ts=trace.toTimeSeries()` to convert a `Trace` object in ObsPy into `TimeSeries`. This will be equivalent to `ts=Trace2TimeSeries(trace)`. This can be done with just one line when the Trace2TimeSeries is defined:
```
Trace.toTimeSeries= Trace2TimeSeries 
```
However, when implementing this, I found out that the built-in types cannot be monkey patched like this, so we cannot provide `dict.toMetadata` through the same trick.

Further looking into the issue, I found that there is a [package](https://github.com/clarete/forbiddenfruit) that enables monkey patch with built-in types. This, however, seems to be pretty hacky and not recommended by some people (the name of the package is absolutely a strong indication). So, I just want to hear your opinion on this before moving forward on this.

**Comment by pavlis** [comment]
Doesn't strike me as that hard to implement wrappers that would be most convenient to do that kind of thing.  That depends on the number of wrapper functions that would need to be written, however, and I don't have a feel how many functions that might be.   Also not that sure that using the object form is adds that much functionality or usability.   I began life, however, as a procedural programmer so my view may be skewed.

**Comment by wangyinz** [comment]
I decide not to use monkey patch on the built-in types.
