### ISSUE TITLE
software build structure

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#6]
This is a top level issue for this project we should not take lightly.  
1.  Should be use classic unix make as the builder or something newer like Cmake?   The answer partly depends upon how much we want to make this work on nonunix platforms?   I would prefer make as I know it well, but I'm an old fart and there may be better alternatives today that I'm unaware of.  Then again, most build systems for open source I see still use make although some (e.g. boost) just create make files for unix systems and something else for windows (I think that is true for boost, but I've not done it).  
2.   Even if we use a make system we need a framework.   I am familiar with Antelope's system, but it has a serious problem.  For reason's I've never understood BRTT people tell me they could never find a way to mesh this with GNU's make mechanism.   Does anyone have an alternative to Antelope's approach we could use?   I can quickly hack what I took from the old open-source version of Antelope called Datascope and used for the plane wave migration package if others are ok with that.   

This decision is important as it could be hard to back out of a mistake once this repository starts to get populated.  We also want to make sure it is not a barrier to future contributors from the community.  i.e. we need to KISS this one

**Comment by pavlis** [comment]
Wonder if you could save me some time on something with cmake.  If not, I'll dig.   I'm having some link issues on linux (uits machines). I'm pretty certain are related to the fact that the unix loader scans any library only once.   Hence, link lines often have to have constructs like
blah   -L/mylibdir -lmylib -lboost_thread -lmylib
Made that up, but the point is -lmylib appears twice and needs to appear twice.

I think I'm having this problem with changes I made for an error logging object added as a series of test in the test_md program.   The issue is I cannot for the life of me find a log file that shows what line make ran to link the program.   Actually, maybe it is a make configuration parameter I'm used to seeing in antelope's makefile system.   i.e. I'm used to seeing compilations echo every line they run,   Maybe the cmake configuration is turning that off?   Any ideas?

**Comment by pavlis** [comment]
Well, the problem wasn't what I thought.  It was not a linking issue but a oddity not worth describing.  

Question does remain, however, about why make created by our current cmake configuration does not echo the lines it executes.  I've always found that invaluable to sort out linking problems.

**Comment by wangyinz** [comment]
I actually mentioned this earlier. The following options of the cmake command will show everything you need. 

> I think the most helpful trick are the `--debug-output`, `--trace`, and `--trace-expand` options. They can tell you what exactly cmake is doing behind the scene.
