### ISSUE TITLE
Ensemble wrappers are broken

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#66]
Something has broken the ensemble pybind11 wrappers.  Well, maybe they never worked but I think I did the kind of test below previously.   Just run the following little script and you should get the same problem:
```
import ccore
x=ccore.CoreSeismogram(100)
y=ccore.Seismogram(x)
ens=ccore.SeismogramEnsemble
ens.member.append(y)
```
Note append normally works with std::vector containers wrapped with pybind11.   At least this little test does for me:
```
z=ccore.CoreTimeSeries(100)
len(z.s) # returns 100 as expected
z.s.append(20.0)
len(z.s) # returns 101 because append acts like push_back in C++
```
When I run the small script for a SeismogramEnsemble I get this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'property' object has no attribute 'append'
```
I get exactly the same in macos and linux.  

What the message says is for some reason the pybind11 wrappers have  made the std::vector container in the SeismogramEnsemble look like something marked as an @property.   Any ideas what would cause this?   I'm going to try to zero in on this by commenting out portions of the wrappers I suspect are causing this.  I'll enter what I find if that works, but if can help focus this it would be great.  Look for updates

**Comment by pavlis** [comment]
Update:   removing all the new stuff you added did not change the error.  I wonder if the problem is that we aren't making use of this construct that is already in the wrapper file:
```
  py::bind_vector<std::vector<double>>(m, "DoubleVector");
  py::bind_vector<std::vector<TimeSeries>>(m, "TimeSeriesVector");
  py::bind_vector<std::vector<Seismogram>>(m, "SeismogramVector");
```
I note, however, the DoubleVector works but the ones used by Ensembles do not.   I'm now stumped.

**Comment by wangyinz** [comment]
I think that's just a syntax issue. You probably should run `ens=ccore.SeismogramEnsemble()` instead of `ens=ccore.SeismogramEnsemble`. The latter is basically assigning alias of the class.

**Comment by pavlis** [comment]
Awsome!   That was indeed it.   Kind of a weird syntax oddity.   Particularly strange for a C++ programmer where the standard has evolved that you get a compilation error if you use a construct like SeismogramEnsemble x();  - you can't use the parantheses.   In some ways I think it is the same as in C++ it is really just a declaration and the default constructor is not actually called.
