### ISSUE TITLE
MsPASSError handling

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#68]
In our meeting today we discussed how to implement error handlers in python wrappers.  We discussed the problem that pybind11 was mapping MsPASSErrors automatically into RuntimeError exceptions.   It was suggested we might just be able to have a block with MsPASSError handlers and it would just work.  A simple test I just did showed I don't think it will be that easy.

I ran a portion of the test_algorithms code in ipython so it has some of the variables below defined.   Let me show you want happens first with a code section a RuntimeError handler:
```
try:
    twin=mspass.TimeWindow(-5.0,-3.0)
    d=mspass._WindowData(ts,twin)
except RuntimeError as err:
    print(str(err))
```
produces
```
WindowData(TimeSeries):  Window mismatch
Window start time=-5 is sample number -50
Window end time=-3 is sample number -30
Parent seismogram has 1000 samples
```
Which is the message string in a MsPASSError thrown by that function that is produced from an override of the method in std::exception.  Have many examples of simpler errors from existing code base.  The problem we need to solve is not the message, but the fact that in mapping this to std::exception we cannot retrieve the "ErrorSeverity" code to handle different levels of errors differently.   

When I replace this same block with a MsPASSError handler 
```
try:
    twin=mspass.TimeWindow(-5.0,-3.0)
    d=mspass._WindowData(ts,twin)
except mspass.MsPASSError as err:
    print(str(err))
```
I get this error from the interpreter:
```
raceback (most recent call last):

  File "<ipython-input-2-227dd157a9ef>", line 4, in <module>
    except mspass.MsPASSError as err:

TypeError: catching classes that do not inherit from BaseException is not allowed
```
Unless I read this wrong this shows we will need to implement a custom exception type with pybind11 - it isn't as easy as hoped.  

The pybind11 documentation [is here](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html) and it doesn't look as bad I remembered.   I'll experiment with this a bit and see if I can make this work.

**Comment by JiaoMaWHU** [comment]
understood, thanks Gary, let's see how it goes

**Comment by pavlis** [comment]
Made some progress, but I think someone who knows more about python than me needs to take it the next step.  I just checked in a change to the pybind11 wrappers.   I did two things:
1.   I fixed a mistake wherein MsPASSError had no binding for it's "severity" method.   It is, in fact, the severity information that is the  current problem.  An error handler needs to know the nature of the error thrown as it will want to handle different levels of "badness" differently.   
2. I added this line as the simplest solution to the binding code:
```
py::register_exception<mspass::MsPASSError>(m,"MsPASSError");
```
However, that created a problem that import of ccore complained about multiple symbol definitions for MsPASSError.  I got around that by changing the class definition line to this:
```
py::class_<mspass::MsPASSError,std::exception>(m,"_MsPASSError")
    .def(py::init<>())
    .def(py::init<const MsPASSError&>())
    .def(py::init<const std::string,const char *>())
    .def(py::init<const std::string,mspass::ErrorSeverity>())
    .def("what",&mspass::MsPASSError::what)
    .def("severity",&mspass::MsPASSError::severity)
  ;
```
Noting that includes the additoin of the severity method definition.  

Well, this works in the sense that I can now use a construct like this and it will at least run:
```
try:
  code throwing an exception
except mspass.MsPASSError as err:
  print(str(err))
```
Problem is if you add in the error handler print(err.severity()) it fails.  

I think what is happening is the simple approach I used here isn't doing much more than what the default is other than defining a symbol MsPASSError.   I don't know enough about python exceptions (maybe you guys don't either) in general to be sure to know how to fix this.  I looked at the test_exceptions code in pybind11, but it didn't help me much in how to solve this problem.  

I am pretty sure we need to do some magic with register_exception_translator but I don't really understand their examples well enough to know how to even start.  

Let me make it clear that what we need is that within a handler we need to be able to deal with this kind of construct one way or the other:
```
except mspass.MsPASSError as err:
  sevlev=err.severity()
  if(sevlev==ErrorSeverity.Invalid):
    do something
  elif(sevlev==ErrorSeverity.Fatal):
   abort
  else:
    normally post the message to the elog of the data
```
A crude solution just occurred to me if we can't crack this nut.   We could change the what method to concatenate the posted error message and some string or int representation of what "severity" means.  We'd need a stock function to then parse the string to get severity.   I'd rather do it right than go that route, but it would work at the cost of some efficiency.

**Comment by JiaoMaWHU** [comment]
Hey Gary, understood our problem. I have a question, is the "what" method working fine? if it is, it does not make sense that the "severity" method is not working. 

And it seems we don't immediately need a fix to get started on the wrapper class coding, but anyway we eventually need it.

**Comment by wangyinz** [comment]
Yes, we can revise the error handling part later in the wrapper code. I need to look into the pybind11 code to see how to fix it.

**Comment by wangyinz** [comment]
After some research and trying, I found that this feature is not supported by pybind11. There are quite a few request in their issues, and there is even a pull request (https://github.com/pybind/pybind11/pull/2333) adding that feature there. It seems the pybind11 developers have not found a efficient way to handle attributes in customized exceptions. I think we will have to go with the string or int representation route now.

**Comment by pavlis** [comment]
Good find.  Definitely agree we don't want to use the new stuff the author of that issue posted or we would need a special fork of pybind11 - a really bad idea for multiple reasons.

This should be easy to implement.  I'm going to change the what method to produce a string of this format:
```
message:severity_string
```
where severity_string will be a string version of the ErrorSeverity enum class.  Specifically so other can proceed while I finish this the string will be versions of the enum names.  That is:
```
Fatal
Invalid
Complaint
Debug
Informational
```
I'm planning to use the ":" character as the separator because most things in ccore already post algorithm:message so it is consistent.   

For speed I will also implement a couple C++ functions to use for testing these message strings.   I'm thinking it would be convenient to have two:
```
bool message_says_data_bad(const string messagestring);   //maybe too verbose
string message_error_severity(const string messagestring);
```
Where the first would be used for a standard test for Invalid and would be use in python wrappers with this logic:
```
if(message_says_data_bad(err.what())):
  d.kill()
```
The second would be a more generic interface to query what level error was encountered.

For C++ programmers, in particular, I will at this convenience function:
```
ErrorSeverity string_to_error_severity(const string s);
```
Perhaps should wrap the convenience function anyway.  However, the enum class syntax for pybind11 is at best confusing and probably should be avoided for any user interactions.   I say that because it is (a) rather verbose, and (b) confusing to me as a C programmer because of a syntax different (e.g. ErrorSeverity::Invalid in C++ becomes ErrorSeverity.Invalid).   I think I'll include the wrapper anyway as it should be faster than implementing such a think in python.

**Comment by pavlis** [comment]
I am still testing the idea here for handling ErrorSeverity, but thought I should pass on some minor names changes I made to the above.  Important if either of you are trying to utilize this new feature for python functions.  

First, here is the C++ prototype from MsPASSError.h with the doxygen comments:
```
/*! \brief Test if a thrown error indicates data are no longer valid.

Errors vary in severity.  Use this function as fast test for an error so
severe an algorithm failed and any subsequent use of the data is ill advised.
*/
bool error_says_data_bad(const mspass::MsPASSError& err);

/*! \brief Return a string representation of error severity.

This function uses the what method to retrieve the message string with the
error severity appended.  It then simply returns the keyword defining the
error code contained in the message.   The list is:  Fatal,Invalid,suspect,
Complaint,Debug, or Informational.   It will return Fatal if there is no
match to any of the keywords assuming something has corrupted memory for
that to happen.
*/
string parse_message_error_severity(const mspass::MsPASSError& err);
/*! \brief return message severity as an ErrorSeverity enum class.

ErrorSeverity is bound with pybind11 and provides a way to define the
severity of an error.  This function is a close companion to parse_message_error_severity.
In fact, in the current implementation it calls parse_message_error_severity and converts
the result string to an ErrorSeverity it returns.    That process has a small
overhead and it is largely a decision of asthetics whether or not to use this
function of parse_message_error_severity.
*/
mspass::ErrorSeverity message_error_severity(const mspass::MsPASSError& err);
```
For the moment I changed the names slightly in the python bindings.   I would like opinions on which you think are preferable.  My inclination is to make the C++ names the same as the python names as they are a bit less verbose, but in our next meeting perhaps we can reach a concensus.   Anyway, here is the pybind11 section for these:
```
m.def("error_says_data_bad",&mspass::error_says_data_bad,
    "Test if what message from MsPASSError defines data as invalid and should be killed")
  ;
  m.def("error_severity_string",&mspass::parse_message_error_severity,
    "Return a string defining error severity of a MsPASSError exception")
  ;
  m.def("error_severity",&mspass::message_error_severity,
    "Return an ErrorSeverity object defining severity of a MsPASSError being handled")
  ;
```
The first uses the same name and should be the most common trap for an error in a ccore function.   i.e. any call to ccore for a Seismogram or TimeSeries object should contain this construct:
```
# assume x is a TimeSeries or Seismogram object
try:
  foo=ccorefunction(x)
except MsPASSError as err:
  if(mspass.error_says_data_bad(err)):
    foo.kill()   # sometimes x.kill() if ccorefunction is altering x in place (common)
    foo.log_error(err)
```
Noting the above is currently theoretical and assumes this will work as implemented.

The other two would be used only if an error handler needed to deal with errors of a less severe nature.  One might, for example, throw a "Questionable" message and want to exclude those.   Because those two functions are not of immediate interest but added for completeness, the name chosen is soft and we could change it you guys think it is needed.

I also thing "error_says_data_bad" is too verbose, but I couldn't come up with anything else that makes the code more or less self documenting.   I remember a colleague who was into writing cryptic code with only short symbols like "db" and "ax" telling me "don't your finger's get tired" when commenting on my coding style.    His code, however, was impenetrable to understand.  Hopefully, constructs like this help make what the code does easier to understand without excessive comments.

**Comment by pavlis** [comment]
Update:   initial testing results are not encouraging.   I can catch a newly defined MsPASSError, but overriding the what method for std::exception does not seem to be working.  This is going to take some more digging.

**Comment by pavlis** [comment]
This is becoming increasing frustrating.   Have been off this topic for over a week when the computer I was using died.   After restoring the data onto a new computer I have spent a fair amount of time on this today and remain puzzled.   The following is not in the original order but it records the sequence I've been through that has me puzzled.  

First, here is more or less where I started.  Let me show you what happens when I use the wrapper code:
```
py::class_<mspass::MsPASSError>(m,"MsPASSError")
    .def(py::init<>())
    .def(py::init<const MsPASSError&>())
    .def(py::init<const std::string,const char *>())
    .def(py::init<const std::string,mspass::ErrorSeverity>())
    .def("what",&mspass::MsPASSError::what)
    .def("_message",&mspass::MsPASSError::core_message)
    .def("severity",&mspass::MsPASSError::severity)
  ;
py::register_exception<mspass::MsPASSError>(m, "MsPASSError");
```
This is pretty much the stock simple approach described in the pybind11 documentation.   ccore builds find with this construct, BUT here is what happens if you try to even get started with that version:
```
import ccore as mspass                                                                                                                                                 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d3095c1fe810> in <module>
----> 1 import ccore as mspass

ImportError: Error during initialization: multiple incompatible definitions with name "MsPASSError"
```
The reason is that apparently we can't use that name that way.   

First let me show that the wrapper for MsPASSError is functioning as it should.   I comment out the py::register_exception line and get the following outputs in a simple set of tests:
```
e1=mspass.MsPASSError('test message 1 with string constructor','Invalid')
e2=mspass.MsPASSError('test message 2 using ErrorSeverity',mspass.ErrorSeverity.Fatal)
e1._message()
'test message 1 with string constructor'
 e1.severity()
ErrorSeverity.Invalid
e2._message()
'test message 2 using ErrorSeverity'
e2.severity()
ErrorSeverity.Fatal
```
i.e. I can call the severity and _message(wrapped) methods and they work and show all is fine.  There seems to be some weird type mismatch in what(), however, as I get this if I try to use it in this construct:
```
>>> e1.what()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte
>>> e2.what()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte
``` 
Noting the difference of byte 0xa0 and 0x90 for e1 and e2 respectively.   The weird thing is if I insert a print statement in the code for what(), which for the record is this (with the print statement):
```
virtual const char * what() const noexcept override
	{
		string s2ret(this->message);
  	s2ret += ":";
  	string es=severity2string(this->badness);
  	s2ret += es;
		cout << "what method should return this string:"<<endl<<s2ret.c_str()<<endl;
  	return s2ret.c_str();
  };
```
Running that with this shorter script has this result:
```
e1.what()                                                                                                                                                              
what method should return this string:
test message 1 with string constructor:Invalid
''
```
i.e. the string s2ret string isn't being properly mapped back somehow.  How and why is what I'm not understanding, but I think it is fundamentally why this doesn't work with the exception mechanism.   

Last example is if I use a variant of the pybind11 documentation examples on how to create a custom exception (retaining that print statement) like this:
```
static py::exception<mspass::MsPASSError> exc(m, "MsPASSError");
  py::register_exception_translator([](std::exception_ptr p) {
    try {
        if (p) std::rethrow_exception(p);
    } catch (const MsPASSError &e) {
        exc(e.what());
    }
  });
```
Now let's run that on a ccore constructor I know will throw a MsPASSError.  
```
 x=mspass.MetadataDefinitions('foo')                                                                                                                                    
what method should return this string:
bad file:Invalid
---------------------------------------------------------------------------
MsPASSError                               Traceback (most recent call last)
<ipython-input-2-e97641225a57> in <module>
----> 1 x=mspass.MetadataDefinitions('foo')

MsPASSError:
```
Note the print statement produces what I expect the what method to return, but when it goes through pybind11 the output is null.   The print statement shows that the what method called in the wrapper code was executed, BUT the return got garbled and ended up in this case showing null.  

So it seems the problem here is something about the way pybind11 is handling the const char* of the what method.  I'm wondering if this is maybe a mismatch of gcc/g++?   What I know is that with C++11 strings and char * are less rigidly typed than they were in older days.  i.e. there seem fewer compiler errors if I'm not careful about mixing strings and C char* things.  That is, however, a total guess and it could be a red herring to use a weird idiom.   I'm just mystified and can't seem to find any combination that makes this work.  

Do either of you have a more fundamental understanding of how python handles exception?   I note one more thing in closing.   
```
try: 
    x=mspass.MetadataDefinitions('foo') 
except mspass.MsPASSError as err: 
    print(err) 
    y=err 
```
returns this
```                                                                                                                                                                  
what method should return this string:
bad file:Invalid

```
Noting the last line is an empty string returned by print(err).  My final point is what you get with dir(y):
```
['__cause__',
 '__class__',
 '__context__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__suppress_context__',
 '__traceback__',
 '__weakref__',
 'args',
 'with_traceback']
```
My reading says this is the contents of the python base class Exception.   Further strengthened by the top section of help(y):
```
Help on MsPASSError object:

class MsPASSError(builtins.Exception)
 |  Common base class for all non-exit exceptions.
 |  
 |  Method resolution order:
 |      MsPASSError
 |      builtins.Exception
 |      builtins.BaseException
 |      builtins.object
 |  
 |  Data descriptors defined here:
 ...
```
So, I think this says MsPASSError is a child of Exception, but what I don't get is how pybind11 is supposed to alias std::exception.what() to which method of Exception?  I cannot find this anywhere, but maybe it is something basic in python I just don't know - I am fairly new at this language.

A very long comment, but wanted to get this down for the record to record what I now know.   I'm stumped and any ideas would be appreciated.

**Comment by wangyinz** [comment]
I didn't see any real problems in your implementation, so I just tried stepping through the lines around the `what()` method trying to understand why it returns an empty string. Turns out somehow the execution is not linear. For example, if we step through the following code:
https://github.com/wangyinz/mspass/blob/50061f29f803ae2a03886d86c0b92815b4e63043/cxx/src/lib/utility/MsPASSError.cc#L62-L68
this is how it behaves:
```
Breakpoint 1, mspass::MsPASSError::what (this=0xbb12d0) at /home/iwang/mspass/cxx/src/lib/utility/MsPASSError.cc:64
64        string s2ret(message + ":" + severity2string(badness));
(gdb) n
65        char * cstr = new char [s2ret.length()+1];
(gdb) n
66        std::strcpy (cstr, s2ret.c_str());
(gdb) n
67        return cstr;
(gdb) n
64        string s2ret(message + ":" + severity2string(badness));
(gdb) print(s2ret)
$1 = "maspass_data_directory procedure:  required environmental variable=MSPASS_HOME is not set:Invalid"
(gdb) n
67        return cstr;
(gdb) print(s2ret)
$2 = "\000\000\000\000\000\000\000\000data_directory procedure:  required environmental variable=MSPASS_HOME is not set:Invalid"
(gdb) n
68      }
(gdb) n
pybind11::exception<mspass::MsPASSError>& pybind11::register_exception<mspass::MsPASSError>(pybind11::handle, char const*, _object*)::{lambda(std::__exception_ptr::exception_ptr)#1}::operator()(std::__exception_ptr::exception_ptr) const (__closure=0x0, p=...) at /home/iwang/mspass/cxx/build/pybind11/include/pybind11/pybind11.h:1823
1823            } catch (const CppException &e) {
```
As you can see the return line is executed twice, and at the second time (when it actually returns), the content of `s2ret` is padded with a bunch of `\000`. That's why the returned cstring appears to be empty. I could not understand how this could happen, but did find a solution, which is what have shown above. I have to copy the string into a char * to circumvent that behavior. 

Now the MsPASSError is behaving as expected. You can do things like:
```
>>> try: 
...     raise mspass.MsPASSError('test message 1 with string constructor:Invalid')
... except mspass.MsPASSError as err: 
...     print(err) 
... 
test message 1 with string constructor:Invalid
>>> try: 
...     x=mspass.MetadataDefinitions('foo') 
... except mspass.MsPASSError as err: 
...     print(err) 
... 
maspass_data_directory procedure:  required environmental variable=MSPASS_HOME is not set:Invalid
```

**Comment by wangyinz** [comment]
hmmm... just realized I am explicitly introducing a memory leak here...

**Comment by pavlis** [comment]
Marvelous - I so love working with you.  It is always great to have a collaborator who you can punt to like this and get a solution, and especially as fast as you did that!  

Yes, that would be a memory leak, but a solvable one if we can understand the fundamental problem here.  I am wondering if this is actually a gcc compiler bug.   You might want to test this with clang to see if it behaves the same.  

This gives me some ideas for a workaround that won't have a memory leak.   I'm working on a hypothesis that the compiler messes up in asking it to deal with too many things at once in that return call that confuse it.  Normally in C/C++ a return is an automatic variable, which by definition is not const.   Here we are asking for a const char * return (we have to to match the type signature of std::exception)  and I'm not sure how the compiler will handle the memory management for such an entity.   Normally, as you know, a char * is a pointer to some memory location.   One of the common sources of bugs in regular C code is forgetting that the * means a pointer and all the standard stuff is just convenience.   I won't dwell on that, but this is what makes me suspicious that the const stuff is confusing the way the compiler handles this.   

I'll see if I can fix this and not create a leak.  Again thanks for the very quick help - I was stumped.

**Comment by pavlis** [comment]
Well, none of my ideas panned out.  I tried two things that didn't help:
1.  Making a temporary const char *s=s2ret.c_str() and returning that - did nothing.
2.  I tried a shared_ptr implementation that was a bit more complicated but also didn't work:
```
std::shared_ptr<const char *> sptr = std::make_shared<const char *>(s2ret.c_str());
return *sptr;
```

I confirm we can make it work with strdup, but that is definitely a memory leak.   I'm inclined to let it leak for now because exceptions by definition are supposed to be exceptional and this leak is only called when what is called, which is often, so we do need to fix it eventually.   Next step, I think, is to verify if clang shares this issue.

**Comment by wangyinz** [comment]
Yeah, always a pleasure to resolve tricky issues like this.

Actually, I was running out of time when realized the memory leak, and I am now finally back to work on it a little bit more. It is always a good idea to take a break, and now I understand exactly what the problem was. 
https://github.com/wangyinz/mspass/blob/50061f29f803ae2a03886d86c0b92815b4e63043/cxx/src/lib/utility/MsPASSError.cc#L62-L68
It is that the `s2ret` went out-of-scope when we return `s2ret.c_str()`. Because the return value of `string.c_str()` is a const char* that points to the memory address within the string object. Once we are outside of the `what()` method, that memory is released, and I think where the `\000` comes from.

**Comment by wangyinz** [comment]
> Well, none of my ideas panned out. I tried two things that didn't help:
> 
> 1. Making a temporary const char *s=s2ret.c_str() and returning that - did nothing.
> 2. I tried a shared_ptr implementation that was a bit more complicated but also didn't work:
> 
> ```
> std::shared_ptr<const char *> sptr = std::make_shared<const char *>(s2ret.c_str());
> return *sptr;
> ```
> 
> I confirm we can make it work with strdup, but that is definitely a memory leak. I'm inclined to let it leak for now because exceptions by definition are supposed to be exceptional and this leak is only called when what is called, which is often, so we do need to fix it eventually. Next step, I think, is to verify if clang shares this issue.

Interestingly that we are posting at the same time. Anyway, yep, none of the pointer solutions works because exactly the problem I just mentioned. It is the memory that these pointers pointing to got released after return is called.

**Comment by pavlis** [comment]
Ahh - that totally makes sense.   A very subtle issue in pybind11.  That would never happen in a C program.  Since pybind11 adds a layer between the python and C++ function I can completely see now that happens.   So glad you found a solution.

**Comment by pavlis** [comment]
Well, we aren't quite there yet, I'm afraid.   I think this is one you can solve easier than me as I think the solution may be on the python side.  

The problem comes testing to see if the new functions I created to use MsPASSError work.  Unfortunately, they don't.   First, this block works as expected:
```
try:
    x=mspass.MetadataDefinitions('foo')
except mspass.MsPASSError as err:
    print(err)
```
Yielding the correct message:  bad file:Invalid

This variant, however, is the issue:
```
try:
    x=mspass.MetadataDefinitions('foo')
except mspass.MsPASSError as err:
    print(err)
    b=mspass.error_says_data_bad(err)
```
yields this:
```
MsPASSError: bad file:Invalid

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-16-3ded2758428f> in <module>
      3 except mspass.MsPASSError as err:
      4     print(err)
----> 5     b=mspass.error_says_data_bad(err)

TypeError: error_says_data_bad(): incompatible function arguments. The following argument types are supported:
    1. (arg0: mspass::MsPASSError) -> bool

Invoked with: MsPASSError('bad file:Invalid',)
```
which I find mysterious for two reasons.  (1) the "invoked with" looks wrong to me, (2) why is this giving a type error anyway?  The reason I say the later is that if I insert a type(err) line in exception block I get `<class 'mspasspy.ccore.MsPASSError'>`.  

If we can't fix this problem easily it might be easier to just make a python function with the same functionality as error_says_data_bad.   Could you have a look at this and see if you can solve this problem?

**Comment by wangyinz** [comment]
I just looked at the pybind11 code and figured that the `error_says_data_bad()` won't work. The problem here is exactly the same as previous, where the `MsPASSError` class is not bind to Python as a normal object. The `register_exception` binding is really only translating the `what()` string into Python, and the MsPASSError exception in Python is not much related to the original MsPASSError object in cxx. Thus, it is a type error because they are different types under Python. The MsPASSError exception in Python has no member variables or methods like the ones called within `error_says_data_bad()`. 

There are only two ways around it. We can either write a string parser that interprets the full error message, or correctly bind the `MsPASSError` object with something other than pybind11.

**Comment by wangyinz** [comment]
OK, I think I found a cleaner solution. Working on it right now.

**Comment by wangyinz** [comment]
Well, turns out it didn't work as I expected, but I do find a better solution than we previously had. See below:
https://github.com/wangyinz/mspass/blob/3e422602a80aceaee445527ef2e1aee7f6a7141d/cxx/python/mspass_wrapper.cpp#L985-L1030
I initially wanted to use that PyErr_SetObject line to throw a custom exception type built with a hybrid of pybind11 and CPython code. That attempt failed due to some incompatibility from `pybind11_object` that I don't quite understand. I suspect it is essentially the same problem as the one in https://github.com/pybind/pybind11/pull/2333. 

Anyway, current implementation is not at all bad given that it is mostly using standard pybind11 constructs. We can now access the `what` and `severity` methods in Python like this:
https://github.com/wangyinz/mspass/blob/3e422602a80aceaee445527ef2e1aee7f6a7141d/python/tests/test_ccore.py#L494-L505
I know the `args[0]` and `MsPASSError(_MsPASSError())` there are ugly, but we will have to live with that until a better (potentially more complex) solution is found.

**Comment by wangyinz** [comment]
OK. Thanks to this [great write-up](https://www.pierov.org/2020/03/01/python-custom-exceptions-c-extensions/) that I found this morning. I am able to follow the initial idea of using a hybrid of pybind11 and Python C API to implement a clean interface for MsPASSError. The relevant code are the following:
https://github.com/wangyinz/mspass/blob/35dac00a82339f3551c21843f1f9286c528aa691/cxx/python/mspass_wrapper.cpp#L400-L446
https://github.com/wangyinz/mspass/blob/35dac00a82339f3551c21843f1f9286c528aa691/cxx/python/mspass_wrapper.cpp#L1033-L1068
The comment already described how it is implemented. The code itself does look complicated, but it is already the cleanest one comparing to the other examples from that write-up. Most of the code is not at all intuitive so I am glad that we are able to follow that great example.

This is how it looks like in Python:
https://github.com/wangyinz/mspass/blob/35dac00a82339f3551c21843f1f9286c528aa691/python/tests/test_ccore.py#L493-L503
As you can see we can directly access the `message` and `severity` attributes of a MsPASSError object thrown from either C++ or Python code.

**Comment by pavlis** [comment]
Cool, I see how that works and it makes sense - mapping methods to args of the python base exception class.  Well done  - again it is so good to have a partner who is better than me.

**Comment by wangyinz** [comment]
Well, only slightly better in python. 

I later updated the implementation so that the custom PyMsPASSError object can parse a sting to corresponding ErrorSeverity type.
