### ISSUE TITLE
CoreSeismogram load data

### ISSUE THREAD

**Issue by JiaoMaWHU** [wangyinz/mspass#83]
@pavlis Hey Gary, I saw this CoreSeismogram constructor:
`CoreSeismogram (const mspass::utility::Metadata &md, const bool load_data=true)` in
 https://wangyinz.github.io/mspass/cxx_api/mspass.html#mspass-namespace. 

Can we rely on this load_data to read data for us? though I've already implemented such a method in python. 

If we can, is there any load data constructor for TImeSeries? I didn't find it.

**Comment by wangyinz** [comment]
I think we should just ignore that on the Python side...
