### ISSUE TITLE
Database Attribute name API

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#9]
I am working on (minor) conversion of the SEISPP objects AttributeMap (see http://www.indiana.edu/%7Epavlab/software/seispp/html/class_s_e_i_s_p_p_1_1_attribute_map.html   ) and AttributeCrossReference ( http://www.indiana.edu/%7Epavlab/software/seispp/html/class_s_e_i_s_p_p_1_1_attribute_cross_reference.html ).

Ian, I'm not sure if you ever used these, but I believe strongly they will be as useful for MongoDB as they proved useful for the Antelope interface.   What they simplify is the thorny problem of internal versus external attribute names.   e.g. CSS3.0 names like origin.lat can be mapped to something like source_latitude.   Another good example is a map to and from SAC's namespace to a (proposed) MsPASS namespace.   This could, for example, allow SAC people to use SAC aliases for standard db attributes allowing them to use SAC names to extract or set attributes.    These two objects provide a core functionality to make that feasible so I'm working to put the revised implementation into mspass.   Now would be a good time to comment on this API.   I've only done one minor tweek so far to the AttributeMap object:  I added an operator[] to get "AttributeProperties" by a standard key defined for the AttributeMap.   The SEISPP version lacked this out of pure laziness since I think I'm the only one who ever used this.  

Anyway, comments are welcome and needed.

**Comment by wangyinz** [comment]
refer to #20 for more updated discussion.
